[package]
name = "macroworking3"
version = "0.1.0"
authors = ["John"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scrap = "0.5.0"
inputbot = "0.4.0"
serde_json = "1.0.50"
serde = { version = "1.0.105", features = ["derive"] }
clipboard = "0.5.0"
rand = "0.7.3"
