[package]
name = "macroworking3"
version = "0.1.0"
authors = ["John"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.2"
scrap = "0.5.0"
inputbot = "0.4.0"
