name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add toolchain
      run: rustup target add stable-x86_64-pc-windows-msvc
    - name: Build
      run: cargo build --target=stable-x86_64-pc-windows-msvc --verbose
    - name: Run tests
      run: cargo test --verbose
